-- Update bot nicknames to realistic gaming nicknames
UPDATE public.bot_players SET nickname = 
  CASE nickname
    WHEN 'Алексей_Петров' THEN 'ShadowDriller92'
    WHEN 'Михаил_Волков' THEN 'OilKing_RU'
    WHEN 'Дмитрий_Козлов' THEN 'BlackGold_Hunter'
    WHEN 'Андрей_Соколов' THEN 'RigMaster2024'
    WHEN 'Владимир_Лебедев' THEN 'PetrolTitan'
    WHEN 'Сергей_Новиков' THEN 'DeepDriller_X'
    WHEN 'Игорь_Морозов' THEN 'GoldenWell88'
    WHEN 'Александр_Федоров' THEN 'EnergyBoss777'
    WHEN 'Николай_Васильев' THEN 'DrillMaster_Pro'
    WHEN 'Евгений_Попов' THEN 'DiamondOil_2024'
    WHEN 'Роман_Семенов' THEN 'FuelGiant_RX'
    WHEN 'Олег_Кузнецов' THEN 'OilEmpire_CEO'
    WHEN 'Денис_Орлов' THEN 'Drillingstar_99'
    WHEN 'Максим_Никитин' THEN 'PowerMagnate_M'
    WHEN 'Артем_Захаров' THEN 'WellPro_Elite'
    WHEN 'Павел_Борисов' THEN 'GasLeader_2024'
    WHEN 'Константин_Григорьев' THEN 'DarkFlow_KG'
    WHEN 'Виктор_Романов' THEN 'ExtractionElite'
    WHEN 'Станислав_Фролов' THEN 'SuccessRig_SF'
    WHEN 'Геннадий_Ковалев' THEN 'OilThrone_King'
    WHEN 'Кирилл_Макаров' THEN 'TitanDriller_K'
    WHEN 'Антон_Давыдов' THEN 'EnergyPower_AD'
    WHEN 'Юрий_Белов' THEN 'WellKing_Supreme'
    WHEN 'Иван_Козин' THEN 'OilDynasty_IV'
    WHEN 'Арсений_Жуков' THEN 'DarkHeart_Driller'
    WHEN 'Валерий_Крылов' THEN 'RigEmpire_VK'
    WHEN 'Матвей_Гусев' THEN 'VictoryEnergy_M'
    WHEN 'Даниил_Савельев' THEN 'OilForce_DS'
    WHEN 'Егор_Тихонов' THEN 'EliteWell_ET'
    WHEN 'Глеб_Калинин' THEN 'FuelBoss_GK'
    WHEN 'Владислав_Панов' THEN 'CrownOil_VP'
    WHEN 'Руслан_Медведев' THEN 'DrillEmperor_RM'
    WHEN 'Тимофей_Назаров' THEN 'LightningOil_TN'
    WHEN 'Артур_Голубев' THEN 'EnergyStorm_AG'
    WHEN 'Ярослав_Воробьев' THEN 'OilVortex_YV'
    WHEN 'Степан_Сорокин' THEN 'LegendDriller_SS'
    WHEN 'Марк_Зайцев' THEN 'GoldenFlow_MZ'
    WHEN 'Леонид_Михайлов' THEN 'TitanEnergy_LM'
    WHEN 'Вадим_Королев' THEN 'DarkFlame_VK'
    WHEN 'Богдан_Климов' THEN 'OilStrength_BK'
    WHEN 'Филипп_Щербаков' THEN 'DrillDragon_FS'
    WHEN 'Мирослав_Баранов' THEN 'PhoenixEnergy_MB'
    WHEN 'Лев_Колесников' THEN 'GoldenStorm_LK'
    WHEN 'Ростислав_Карпов' THEN 'OilThunder_RK'
    WHEN 'Святослав_Афанасьев' THEN 'DarkArrow_SA'
    WHEN 'Эдуард_Данилов' THEN 'DrillLightning_ED'
    WHEN 'Родион_Горшков' THEN 'HurricaneEnergy_RG'
    WHEN 'Севастьян_Рыбаков' THEN 'OilAvalanche_SR'
    WHEN 'Платон_Никифоров' THEN 'GoldenVolcano_PN'
    WHEN 'Назар_Силин' THEN 'DarkTornado_NS'
    ELSE nickname
  END;